#!/usr/bin/env node

var fs = require('fs')
  , execSync = require('child_process').execSync
  , util = require('util')
  , ejs = require('ejs')
  , marked = require('marked');


var locale = 'en';
var docDir = __dirname + '/../doc';
var dstDir = '../cocoa/NAMIDI/Resources/NASequencer.help/Contents/Resources';

var contents = {
  overview:        docDir + '/' + locale + '/' + 'overview.md',
  getting_started: docDir + '/' + locale + '/' + 'getting-started.md',
  general:         docDir + '/' + locale + '/' + 'operation-manual-general.md',
  preference:      docDir + '/' + locale + '/' + 'operation-manual-preference.md',
  nas:             docDir + '/' + locale + '/' + 'nas.md',
  abc:             docDir + '/' + locale + '/' + 'abc.md',
  mml:             docDir + '/' + locale + '/' + 'mml.md',
  support:         docDir + '/' + locale + '/' + 'support.md',
  license:         docDir + '/' + 'base' + '/' + 'license.md',
}

var renderer = new marked.Renderer();

// For Help Indexer
renderer.br = function () {
  return '<br/>';
}

function main(argv, callback) {
  var template = fs.readFileSync(docDir + '/template/help.ejs', 'utf-8');
  var dest = dstDir + '/en.lproj/index.html';

  var renderAttrs = {};

  for (var key in contents) {
    var md = fs.readFileSync(contents[key], 'utf8');

    renderer.heading = function (text, level) {
      if (1 == level) {
        return '';
      }
      level += 2;
      return '<a name="'+key+'__'+text+'"></a><h'+level+'>'+text+'</h'+level+'>';
    }

    renderer.link = function (href, title, text) {
      if (href.startsWith('http')) {
        return '<a href="'+href+'" target="_blank">'+text+'</a>';
      }
      else {
        return '<a class="js-transit" href="#'+key+'__'+href.substring(1)+'">'+text+'</a>';
      }
    }

    renderAttrs[key] = marked(md, {renderer: renderer});
  }

  var html = ejs.render(template, renderAttrs);
  fs.writeFileSync(dest, html);

  execSync('rm -f '+dstDir+'/shared/*.png');
  execSync('cp '+docDir+'/shared/*.png '+dstDir+'/shared/');
}

if (!module.parent) {
  main(process.argv.slice(), function(err, code) {
    if (err) throw err;
    return process.exit(code || 0);
  });
} else {
  module.exports = main;
}
