#!/bin/bash

cd `dirname $0`

rm -rf ../release/namidi-cli-*
rm -rf ../doc/dest/
./md_renderer

cd ../bin
cmake -DCMAKE_BUILD_TYPE=Debug ../cli
make clean
make

cd ../
mkdir -p release/namidi-cli-$1
mkdir -p release/namidi-cli-$1/syntax
mkdir -p release/namidi-cli-$1/example

cp doc/dest/* release/namidi-cli-$1/syntax/
cp test/parser/*/*.nas release/namidi-cli-$1/example/
cp test/parser/*/*.abc release/namidi-cli-$1/example/
cp test/parser/*/*.mml release/namidi-cli-$1/example/

cp bin/namidi-cli release/namidi-cli-$1/

cd release/
zip -r namidi-cli-$1.zip namidi-cli-$1/
